### ISSUE TITLE
Google's deprecation date for the v3 sheets API is March 3rd 2020

### ISSUE THREAD

**Issue by stuart-clark-45** [crazy4groovy/google-spreadsheet-promise#1]
Hi there I am getting the following warning although my code does still work for now so I guess they have got the date wrong. 

Hopefully just a case of updating the dependancy? 

```
WARNING! You must upgrade to the latest version of google-spreadsheet!
Google's deprecation date for the v3 sheets API is March 3rd 2020
Bad news - this version of this module will stop working on that date :(
Good news - the new version of the module uses the newer v4 api :)
However, there are breaking changes, so please see the docs site
https://theoephraim.github.io/node-google-spreadsheet
```

Thanks for a great library!

**Comment by crazy4groovy** [comment]
Thanks for the note. Glad you liked it. I'm going to deprecate this module, since google-spreadsheet is now promise based by default, and uses the newer v4 sheets API.
Cheers!
